# Copyright 2018 Shift Devices AG
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Run with Docker:
# docker build --tag shift/mcu-base-tests -f Dockerfile.tests .
#

FROM shift/mcu-base
ENV DEBIAN_FRONTEND noninteractive
WORKDIR /app
COPY . /app

RUN gcc -v
RUN clang -v
ENV CC gcc
RUN cd /app/ && rm -rf docker-build
RUN cd /app/ && mkdir docker-build && cd docker-build && cmake .. -DBUILD_TYPE=test -DCONTINUOUS_INTEGRATION=1 && make && make test
RUN cd /app/docker-build/ && valgrind --leak-check=full --num-callers=40 --suppressions=../.valgrind.supp --error-exitcode=1 bin/tests_api;
RUN cd /app/docker-build/ && valgrind --leak-check=full --num-callers=40 --error-exitcode=1 bin/tests_u2f_hid;
RUN cd /app/docker-build/ && valgrind --leak-check=full --num-callers=40 --error-exitcode=1 bin/tests_u2f_standard;
RUN cd /app/docker-build/ && valgrind --leak-check=full --num-callers=40 --error-exitcode=1 bin/tests_unit;
RUN cd /app && rm -rf /app/docker-build

RUN cd /app/ && mkdir docker-build && cd docker-build && cmake .. -DBUILD_TYPE=test -DCONTINUOUS_INTEGRATION=1 -DUSE_SECP256K1_LIB=ON && make && make test
RUN rm -rf /app/docker-build
RUN cd /app/ && mkdir docker-build && cd docker-build && cmake .. -DBUILD_TYPE=test -DUSE_SECP256K1_LIB=OFF && make
RUN rm -rf /app/docker-build
RUN cd /app/ && mkdir docker-build && cd docker-build && cmake .. -DBUILD_TYPE=bootloader -DUSE_SECP256K1_LIB=OFF && make
RUN rm -rf /app/docker-build
RUN cd /app/ && mkdir docker-build && cd docker-build && cmake .. -DBUILD_TYPE=firmware -DUSE_SECP256K1_LIB=ON && make
RUN rm -rf /app/docker-build
RUN cd /app/ && mkdir docker-build && cd docker-build && cmake .. -DBUILD_TYPE=firmware && make
RUN rm -rf /app/docker-build
ENV CC clang
RUN cd /app/ && mkdir docker-build && cd docker-build && cmake .. -DBUILD_TYPE=test -DUSE_SECP256K1_LIB=ON && make
RUN rm -rf /app/docker-build
RUN cd /app/ && mkdir docker-build && cd docker-build && cmake .. -DBUILD_TYPE=test -DUSE_SECP256K1_LIB=OFF && make
RUN rm -rf /app/docker-build
RUN cd /app/ && mkdir docker-build && cd docker-build && cmake .. -DBUILD_TYPE=bootloader -DUSE_SECP256K1_LIB=OFF && make
RUN rm -rf /app/docker-build
RUN cd /app/ && mkdir docker-build && cd docker-build && cmake .. -DBUILD_TYPE=firmware -DUSE_SECP256K1_LIB=ON && make
RUN rm -rf /app/docker-build
RUN cd /app/ && mkdir docker-build && cd docker-build && cmake .. -DBUILD_TYPE=firmware && make
RUN sha256sum docker-build/bin/*
